//public class Student3 {
//
//    private String name;
//
//    public String getName() {
//        return name;
//    }
//
//    public void setName(String name) {
//        this.name = name;
//    }
//
//
//
//    //public class EncapsulationExample {
//
//
//        public static void main(String[] args) {
//            Student3 student4 = new Student3();
//            student4.setName("icon");
//            System.out.println("Student3 name: " + student4.getName());
//
//        }
//
//   // }
//
//}
